/* eslint-disable @next/next/no-img-element */

function InstallFolders() {
  return <div className="doc-table compact-table"><div><b>macOS</b><code>~/Library/Audio/Plug-Ins/CLAP</code><code>~/Library/Audio/Plug-Ins/VST3</code></div><div><b>Windows</b><code>C:\Program Files\Common Files\CLAP</code><code>C:\Program Files\Common Files\VST3</code></div><div><b>Linux</b><code>~/.clap</code><code>~/.vst3</code></div></div>;
}

export function WowStartContent() {
  return <>
    <p>Put Wow on a sustained chord, a melody or a sample, then bring up Amount until you hear the pitch move. Start with slow Wow for a gentle warble. Blend towards Flutter for faster movement, and add Drift to make the motion less predictable.</p>
    <p>Try it subtly first. A little movement can change the feel of a steady sound; a larger Amount makes the pitch modulation an audible part of the performance. HQ is the default quality setting, so you can start listening without changing it.</p>
  </>;
}

export function WowExplainerContent({ basePath }: { basePath: string }) {
  return <section className="technical-explainer" id="why-clean-modulation-matters"><h2>Why clean modulation matters</h2><p>Pitch modulation changes the speed at which stored audio is read. Most requested read positions land between samples, so the plug-in has to reconstruct values that were never recorded directly. That reconstruction method has a large effect on the output.</p><h3>The interpolation problem</h3><p>A simple interpolator is inexpensive, but it can lose high-frequency level and create tones unrelated to the requested pitch movement. When playback speeds up, frequencies near the top of the input spectrum can be pushed beyond the output Nyquist limit. If they are not removed before resampling, they fold back into the audible band as aliasing, an implementation artifact.</p><p>Those errors are tonally unrelated to the sidebands produced by pitch modulation itself. Frequency modulation naturally creates related components around the original tone. Those are part of the effect.</p><h3>What Wow does</h3><p>Normal, HQ, and Ultra use polyphase windowed-sinc fractional-delay readers. Their low-pass cutoff follows the instantaneous playback rate: around normal speed, nearly the full input band is retained; as the read rate rises, the cutoff moves down far enough to stop content crossing the output Nyquist limit.</p><p>The filter banks are prepared away from the real-time audio thread and interpolated smoothly during processing. Normal uses 80 taps, HQ uses 96, and Ultra uses 128. The increasing tap count tightens spectral accuracy at a higher processing cost. Draft deliberately uses a simpler cubic interpolator.</p><figure className="doc-figure spectrum-figure"><img src={`${basePath}/images/wow-spectrum-comparison.png`} alt="Spectrogram comparing an unfiltered pitch-modulated delay, typical wow and flutter plug-ins, and Oiko Wow" width="1215" height="435" /><figcaption>Matched input, modulation depth, sample rate, level, FFT settings, and render duration. Competing products are anonymised.</figcaption></figure><h3>Reading the comparison</h3><p>The bright central curve is the modulated test tone. The additional arcs and haze around it show energy created by the resampling process. The unfiltered delay folds substantial energy through the spectrum. The middle examples reduce that energy but retain repeated spurs. Wow keeps the intended moving tone and its physically correct modulation sidebands while suppressing the unrelated structure.</p><p>The difference is easiest to hear on exposed high frequencies, extreme settings, and layered modulated signals. On darker or dense material it may be subtle, but clean resampling prevents the artifacts from accumulating.</p></section>;
}

export function WowManualContent({ basePath, includeIntroduction = true }: { basePath: string; includeIntroduction?: boolean }) {
  return <>
    {includeIntroduction && <section><h2>Start here</h2><WowStartContent /></section>}
    <section><h2>Main controls</h2><dl className="manual-list"><div><dt>Wow Rate</dt><dd>Sets wow frequency from 0.1 to 4 Hz.</dd></div><div><dt>Flutter Rate</dt><dd>Sets the flutter frequency from 6 to 30 Hz.</dd></div><div><dt>Wow / Flutter</dt><dd>Blends the two LFOs with constant power.</dd></div><div><dt>Amount</dt><dd>Sets the total pitch movement.</dd></div><div><dt>Drift</dt><dd>Adds repeatable, smoothly changing variation to both LFO rates.</dd></div><div><dt>L/R Phase Offset</dt><dd>Offsets left and right modulation by up to 180°.</dd></div></dl></section>
    <section><h2>Quality</h2><p>HQ is the default. Normal, HQ, and Ultra all use rate-aware windowed-sinc readers with progressively tighter spectral accuracy. Draft uses a lower-cost cubic interpolator for comparison.</p></section>
    <section><h2>Pitch range and latency</h2><p><b>Rate-scaled</b> keeps delay excursion bounded, so faster modulation produces more pitch movement. At 48 kHz it reports about 8.0 ms latency.</p><p><b>Constant</b> keeps the perceived pitch range more consistent across oscillator rates. At 48 kHz it reports about 34.2 ms latency.</p><p>The host is responsible for latency compensation. Changing Pitch Range can make the host restart processing.</p></section>
    <section id="faq"><h2>FAQ</h2><dl className="manual-list faq-list"><div><dt>How do I change the interface size?</dt><dd>Click <b>OIKO AUDIO</b> in the top row of the plug-in, then choose an <b>Interface Scale</b> value from 50% to 200%.</dd></div><div><dt>Where do I install it?</dt><dd>Copy the formats you use into their matching folders, restart the DAW, then rescan plugins.<InstallFolders /></dd></div><div><dt>Are the beta builds signed or notarized?</dt><dd>No. The current builds are not signed for distribution, and the macOS builds are not notarized. macOS and Windows may ask you to allow the plugin before the host can scan it.</dd></div></dl></section>
    {includeIntroduction && <WowExplainerContent basePath={basePath} />}
  </>;
}

export { WeftStartContent, WeftExplainerContent, WeftManualContent, WeftReleaseContent } from './weft-content';

export function WowReleaseContent() {
  return <><section className="release-entry"><div className="release-heading"><h2>0.1.1-beta.3</h2><time dateTime="2026-09-01">1 September 2026</time></div><ul><li>Fixed interface zoom and window resizing in macOS hosts.</li><li>Added a universal macOS archive for Apple Silicon and Intel.</li><li>Includes correctly named Oiko Wow CLAP and VST3 bundles.</li></ul></section><section className="release-entry"><div className="release-heading"><h2>0.1.1-beta.2</h2><time dateTime="2026-08-30">30 August 2026</time></div><ul><li>Added interface scaling from 50% to 200%. Click OIKO AUDIO in the top row to set it.</li><li>The selected scale is restored when the plug-in reopens.</li><li>Added separate macOS CLAP and VST3 builds for Apple Silicon and Intel.</li></ul></section><section className="release-entry"><div className="release-heading"><h2>0.1.1-beta.1</h2><time dateTime="2026-08-26">26 August 2026</time></div><p>First public beta.</p><ul><li>Slow wow and fast flutter modulation with a constant-power blend.</li><li>Repeatable drift and stereo phase offset.</li><li>Draft, Normal, HQ, and Ultra quality modes.</li><li>Rate-scaled and Constant pitch-range modes.</li><li>Mono and stereo CLAP and VST3 builds for macOS, Windows, and Linux.</li></ul></section><section><h2>Known limitations</h2><ul><li>Builds are not signed or notarized.</li><li>Changing Pitch Range changes reported latency and may make the host restart processing.</li><li>Host and platform compatibility is still being established during beta.</li></ul></section><section><h2>Report a bug</h2><p>Use the <a href="https://github.com/oikoaudio/wow/issues/new?template=beta-report.yml">Wow beta report form</a> for bugs and compatibility problems.</p></section></>;
}
