import type { Metadata } from 'next';
import { SiteHeader } from '../site-header';

export const metadata: Metadata = { title: 'Oikontrol | Oiko Audio', description: 'Bitwig controller extensions for Akai Fire and Novation Launch Control XL Mk2. Drum sequencing, melodic generators and hands-on device control.' };

export default function OikontrolPage() {
  const base = process.env.NEXT_PUBLIC_BASE_PATH ?? '';
  return <main>
    <SiteHeader currentProduct="Oikontrol" />
    <section className="oikontrol-intro">
      <p className="index">BITWIG CONTROLLER EXTENSIONS / 2.23.0</p>
      <h1>OIKONTROL</h1>
      <h2>Performance and sequencing for Bitwig.</h2>
      <p>Oikontrol is a Bitwig Studio extension that turns the Akai Fire into an expressive note controller, polyphonic step sequencer and phrase generator built around Bitwig&apos;s clip launcher. Play with pitch bend and glissando. Build your own chord voicings, generate basslines, or work with nested tuplets and ratchets.</p>
      <p>Clip launching, recording and device controls work independently of the sequencers. The OLED shows encoder assignments, parameter values and note or chord names. Mix mode includes RMS levels and peak-hold readings, with an optional multichannel VU meter.</p>
      <p>Fine timing controls let you place individual hits slightly ahead of or behind the beat, giving a rhythm more push or pull. In generative modes, shift the whole pattern by adjusting the clip&apos;s play start without rewriting its notes.</p>
      <div className="actions"><a className="button primary" id="downloads" href={`${base}/downloads/#oikontrol`}>Download ↗</a><a className="button" href={`${base}/manuals/oikontrol/`}>Read the manual ↗</a></div>
      <p className="oikontrol-requirements">Bitwig Studio 6.0 or later · Windows, macOS and Linux</p>
    </section>
    <section className="oikontrol-hardware" aria-label="Supported controllers">
      <article><p className="index">AKAI FIRE / PLAY & SEQUENCE</p><h2>Live input and sequencing</h2><p>Melodic, harmonic and drum input give you three ways to play live. Six sequencing modes cover drum patterns, polyphonic steps, generated melodies, nested rhythms, contrapuntal phrases and editing across multiple clips.</p><p>Shared root, scale and octave settings keep live note input and melodic sequencing in the same musical context, with scales aligned with those in Bitwig.</p><p>Most of the sequencers let you shape velocity, pressure, timbre and pitch expression per note, and apply fresh variations across a phrase.</p></article>
      <article><p className="index">AKAI FIRE / DRUM XOX</p><h2>Drum XOX</h2><p>Start with a familiar drum step sequencer, then shape the groove as it plays. Hold steps to nudge their timing, add accents and fills, or rotate the pattern with live control gestures.</p><p>Edit recurrence and per-note expression, or use Euclidean pattern controls. Drum Pads adds a 64-pad layout, fixed velocity zones and a bongo layout with position-based pressure.</p><a className="button" href={`${base}/manuals/oikontrol/#akai-fire`}>Drum controls ↗</a></article>
      <article><p className="index">AKAI FIRE / NOTE</p><h2>Note and harmonic input</h2><p>The 16×4 grid offers chromatic and in-key layouts. Encoders control pitch bend, Pitch Gliss, modulation and timbre, with another page for aftertouch, breath and pitch expression. Sustain, sostenuto, note repeat and held notes have dedicated buttons.</p><p>Harmonic mode lays out a grid of harmonic shapes that you can play individually or combine to create chords and phrases. Choose one to three notes per pad, spread them across octaves, and switch between Close, Open and Drop 2 voicings. Keep two columns for single bass notes while the rest of the grid plays chords.</p><a className="button" href={`${base}/manuals/oikontrol/#note-mode`}>Note controls ↗</a></article>
      <article><p className="index">AKAI FIRE / POLY STEP</p><h2>Poly Step</h2><p>Select individual notes or chords on the pads, chromatically or within a scale. Latch a chord and add or remove individual notes. Hold existing steps and play a new grip to change their pitches without replacing their other note settings.</p><p>For starting points, chord banks include quartal, suspended, cluster and modal voicings. Keep the exact interval shape or map it through the current scale. Edit note length, recurrence, repeats and expression per step. Root, scale and octave are shared with live note input and the melodic generator.</p><a className="button" href={`${base}/manuals/oikontrol/#poly-step-mode`}>Poly Step controls ↗</a></article>
      <article><p className="index">AKAI FIRE / MELO GEN</p><h2>Melo Gen</h2><p>Choose a pool of notes, then let five generators with different characteristics draw from those notes to create phrases. Explore basslines, motifs and melodic hooks, then adjust density, tension and legato. Keep an idea you like and reshape it, or edit the generated notes directly. Acid produces root-led hooks with accents and slides. Rolling builds repeating bass cells. Octave works with register jumps; Motif develops short repeating figures; Call/Resp follows a phrase with a transformed answer.</p><p>Fixed seeds make the generated results reproducible.</p><a className="button" href={`${base}/manuals/oikontrol/#melo-gen-mode`}>Generator controls ↗</a></article>
      <article><p className="index">AKAI FIRE / NESTED RHYTHM</p><h2>Nested Rhythm</h2><p>Subdivide phrase spans into tuplets, then subdivide selected cells again into ratchets. Both support divisions from 2 to 16. Density removes hits; Cluster concentrates them into a smaller part of the phrase. You can edit individual generated hits for recurrence and expression.</p><p>The design draws on Clarence Barlow&apos;s metric indispensability: some pulse positions do more to establish a metre than others. That informs which hits survive as density falls. Euclidean sequencing is available separately in Drum XOX; Nested Rhythm deals with hierarchical subdivisions and phrase structure.</p><a className="button" href={`${base}/manuals/oikontrol/#nested-rhythm-mode`}>Rhythm controls ↗</a></article>
      <article><p className="index">AKAI FIRE / FUGUE</p><h2>Fugue: one melody, several voices</h2><p>Fugue derives up to three supporting lines from a source melody. Slow one down for a bass part, shift another up the scale, reverse its direction or delay its entrance. Adjust each voice from the encoders to hear related phrases emerge, from simple harmonies to overlapping canons.</p><p>The source melody lives on MIDI channel 1, with the derived voices on channels 2–4. Fugue draws on Bach-style contrapuntal transformations, with independent speed, entry time, direction and scale-degree offset for each supporting line.</p><a className="button" href={`${base}/manuals/oikontrol/#fugue-mode`}>Fugue controls ↗</a></article>
      <article><p className="index">AKAI FIRE / PERFORM</p><h2>Clip launching and recording</h2><p>Launch clips in a vertical or horizontal layout, trigger scenes, or jump across a larger set with Birds-Eye navigation. Record into a chosen slot or the next free slot. Recording can stop at a fixed length, run manually, or round the resulting loop to a whole bar when you stop.</p><p>Mix pages handle track selection, mute, solo and arm. Device pages select and bypass devices, open plugin windows and switch remote pages.</p><a className="button" href={`${base}/manuals/oikontrol/#akai-fire`}>Launcher and recording ↗</a></article>
      <article><p className="index">NOVATION / LAUNCH CONTROL XL MK2</p><h2>Launch Control XL Mk2</h2><p>I like Bitwig&apos;s factory templates for the Launch Control XL, but wanted to keep the user templates available for direct MIDI mapping in synths. The bundled Bitwig script disables them.</p><p>Oikontrol keeps the factory templates and makes the user templates available too. It adds a Drum Machine template with pad selection and audition, chain levels on the faders, and drum-device parameters on the knobs. There&apos;s also a template for accessing several device remote pages at once.</p><p>The arpeggiator template adapts Richie Hawtin and Eric Ahrens&apos; rhbitwig controls for performing with Bitwig&apos;s Arpeggiator.</p><a className="button" href={`${base}/manuals/oikontrol/#launch-control-xl`}>Launch Control manual ↗</a></article>
    </section>
    <footer><p>OIKO AUDIO</p><p>Oiko Audio is a brand of Octofox Ltd.</p></footer>
  </main>;
}
